---
name: 'gh-token'
author: 'GitHub'
description: >
  It is a simple dockerfile/container to help make converting
  GitHub App Authentication into a usable Personal Access Token.
  It can also be used to revoke tokens, or check installations.
inputs:
  ACTION:
    description: >
      Action to perform (generate,revoke,installations)
      ACTION 'generate' will return environment variable: GENERATED_TOKEN
      ACTION 'installations' will return environment variable: INSTALLATIONS
      ACTION 'revoke' will only pass or fail with successful revoke of token
    default: generate
  PRIVATE_KEY:
    description: >
      This is the PRIVATE_KEY from the users created GitHub App.
      The user must pass the file location, or have the contents stored in
      a string like ${{ secrets.PRIVATE_KEY }}
  APP_ID:
    description: >
      The APP_ID for the GitHub App that we are generating
      a Personal Access Token from.
  TOKEN:
    description: >
      (Optional) The GitHub Personal Access Token you want to use.
      This can be for the ACTION: revoke
  DURATION:
    description: The duration of time for the Personal Access Token to live.
    default: 10
  GITHUB_HOSTNAME:
    description: >
      (Optional) this is used for users on GHES. You can change
      from the defult to your GHES api url. Example: mycompany.ghes.com/api
    default: api.github.com
  INSTALLATION_ID:
    description: INSTALLATION_ID from users created GitHub App
runs:
  using: 'docker'
  image: 'Dockerfile'
branding:
  icon: 'check-square'
  color: 'blue'
# You can view https://github.com/github/super-linter#environment-variables
# to see a comprehensive list of all environment variables that can be passed
